### ISSUE TITLE
Patent grant dropped Feb 17

### ISSUE THREAD

**Issue by TomWor** [arielelkin/arielelkin.github.io#10]
Thanks for your article "why-im-not-a-react-native-developer.html".

I just checked with the license for React Native and they dumped the Patent grant part.
Just thought you might want to update it.
https://github.com/facebook/react-native/commits/master/LICENSE

Your original conclusion still stands and I found it very valuable, as I'm currently evaluating cross-platform mobile options for my employer.
Cheers!

**Comment by arielelkin** [comment]
Thanks for bringing that to my attention, @TomWor . 

Fixed via https://github.com/arielelkin/site_source/commit/7193bc4c58ddb63ef22193304eaf0230231f29bb
