### ISSUE TITLE
No date -- why-im-not-a-react-native-developer

### ISSUE THREAD

**Issue by dant00ine** [arielelkin/arielelkin.github.io#6]
I noticed your article why-im-not-a-react-native-developer doesn't include a date. It seems like a lot of good information, but a good researcher needs a date.

 Why not include the date at the top of the article, so people know it isn't from two years ago?

**Comment by arielelkin** [comment]
thanks for the feedback, fixed via https://github.com/arielelkin/arielelkin.github.io/commit/d8d5b0943886a23288bb613ceca6f851daa3e588#diff-9676a74ce61f19794805bf1aee6e6eea
