### ISSUE TITLE
Maybe my most favorite (outdated) article ever

### ISSUE THREAD

**Issue by AckerApple** [arielelkin/arielelkin.github.io#7]
The why not react article, is flat out fantastic. I will book mark and share maybe for the rest of my career. I'm an Angular guy who chose Angular, for the enforcement of Typescript.

I don't have endless time but I did want to throw up some updated details:

1 - Appcelerator doesnt seem the way to go. My collected evidence (popularity, reported issues, releases...blah blah) plus this link support my conclusion on not using Appcelerator: [appcelerator-vs-react-native](http://www.npmtrends.com/appcelerator-vs-react-native)

2 - The article points out a lot of failure points in loose Javascript. It even talks about compilers adding to the Javascript mess........ Well I think its now time and worth pointing out that a language like Angular is enforcing adoption of typing and such useful enforcement techniques through Typescript.

3 - Well, again, can't talk about it enough: Angular4+ really has a place, all over the place, in this article. AngularJs came first, React learned a lot from AngularJs, and then Angular learned a lot from React. This graph here (especially over 2 years time), I think has useful trend like information: [core-vs-react-vs-react-native](http://www.npmtrends.com/@angular/core-vs-react-vs-react-native)

4 - The article never talks about Promises and/or Observers. Callback hell has been completely solved by Promises, Observers. The article's illustration of the guys digging to dig their way out, is fantastic, but the guy who kept digging maybe on to something. AS IF TO SAY "The difference between talented and successful is hard work".... YOU MAY SAY "Work smarter not harder" but popularity can bring about standardization and the overwhelming amount of people building upon web code is resulting in better code than seen in other languages. I AM SAYING: Hard to compete with Open Source software because more people contribute and partake in it for Javascript than any other languages.

5 - Webpack offers hot module reloading. Angular has hot module reloading. React-native may have been a bad choice because it bundled every feature known under the sun in just one package but most of us now know it's far more practical to longevity to only install just the dependencies you need for the project.... [nativescript](https://www.npmjs.com/package/nativescript) has come out and it aims to be react-native without the react. Check this out: [react-native-vs-nativescript](http://www.npmtrends.com/react-native-vs-nativescript)

That's all for now. The players have changed drastically but the game remains the same. That's why this article is so relevant and will be great to use over time.

Thank you very much in kind

_Acker Apple

**Comment by arielelkin** [comment]
Hi @AckerApple, thanks for the feedback. 

Popularity and download counts of a package doesn't make a package better than any other one. I went over this in https://arielelkin.github.io/articles/why-im-not-a-react-native-developer#wider-angles.

You're right that the players have changed, but the fundamental issues (JS, patent, dependencies) are still there. Whether Angular would now be a better alternative is a good question.

**Comment by AckerApple** [comment]
"Popularity and download counts of a package doesn't make a package better" but it sure does spell out when a new technology comes out, has many adopters and then loses even the original adopters over time. Appcelerator has much evidence against it, including the loss of original adopters whom have abandoned it (as seen in less usage then it ever had).

Thank you for the reply
