### ISSUE TITLE
Update licensing issue

### ISSUE THREAD

**Issue by aegis123** [arielelkin/arielelkin.github.io#8]
Maybe the licensing issue should be rewritten since facebook has changed that.

[Relicensing React, Jest, Flow, and Immutable.js](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/)

**Comment by arielelkin** [comment]
Sadly, they haven't for React Native. See https://github.com/arielelkin/arielelkin.github.io/pull/9 

I've updated the article accordingly: https://arielelkin.github.io/articles/why-im-not-a-react-native-developer#october-2017-update-facebook-relicensing
